/**
 * Order Status Constants Configuration
 * =====================================
 *
 * 이 파일은 주문 상태 관리를 위한 중앙 집중식 상수 정의입니다.
 * Notion 데이터베이스와 동기화되어 있습니다.
 *
 * ## 주요 구성요소
 *
 * 1. ORDER_STATUS_CODES: 모든 주문 상태의 숫자 코드 정의
 * 2. ORDER_STATUS_ENUM: 상태 코드와 한글 라벨 매핑
 * 3. ORDER_STATUS: 주문 처리 후 상태 목록 (UI 표시용)
 * 4. STATUS_COLORS: 상태별 색상 정의
 * 5. ORDER_STATUS_COLOR_ENUM: 상태 라벨과 색상 매핑
 *
 * ## 색상 그룹 분류
 *
 * - Orange (#FF8A01): 시작 전 상태 (WAITING)
 *   → 결제완료, 주문접수지연, 환불완료(검증실패), 테이블주문요청
 *
 * - Green (#3AA639): 진행 중 상태 (IN_PROGRESS)
 *   → 주문접수, 픽업대기, 배달진행, 환불처리 등
 *
 * - Blue (#0085E5): 완료 상태 (COMPLETED)
 *   → 픽업완료, 배달완료, 테이블주문취소
 *
 * - Red (#E3211E): 실패/오류 상태 (FAILED)
 *   → 배달실패, 결제실패, 환불실패, 주문요청실패
 *
 * - Grey (#8F8F8F): 환불 완료 상태 (REFUNDED)
 *   → 환불완료, 자동환불완료
 *
 * - 미표시: 색상 없음 (NONE)
 *   → 결제대기중, 테이블주문결제완료
 *
 * ## 상태 코드 범위
 *
 * - 0-10: 기본 주문 처리 (결제, 주문, 픽업, 배달)
 * - 11-14: 환불 처리
 * - 15-18: 결제 검증 및 지연 처리
 * - 19-22: 테이블 주문
 * - 23-29: 오류 및 실패 상태
 * - 30-31: 특수 상태 (환불실패, 로봇하차)
 * - 32-34: 부분 픽업
 *
 * @see Notion Database: https://www.notion.so/592dce08c9674ada85f75b9d6f04ea0d
 * @updated 2025-02-13
 */

// Define base status codes as a single source of truth
const ORDER_STATUS_CODES = {
  PAYMENT_WAITING: 0,
  PAYMENT_COMPLETED: 1,
  ORDER_ACCEPTED: 2,

  PICKUP_WAITING: 3,
  PICKUP_COMPLETED: 4,
  PICKUP_COMPLETED_AUTO: 5,

  DELIVERY_REQUESTED: 6,
  DELIVERY_IN_PROGRESS: 7,
  DELIVERY_COMPLETED: 8,
  DELIVERY_COMPLETED_AUTO: 9,
  DELIVERY_CANCELED: 10,

  REFUND_REQUESTED: 11,
  REFUND_IN_PROGRESS: 12,
  REFUND_COMPLETED: 13,
  REFUND_COMPLETED_AUTO: 14,
  REFUND_FAILED: 30,

  PAYMENT_INVALID: 15,
  REFUND_IN_PROGRESS_INVALID_PAYMENT: 16,
  PAYMENT_FAILED: 23,

  ORDER_ACCEPT_DELAYED: 17,
  PICKUP_RE_REQUESTED: 18,

  TABLE_ORDER_REQUESTED: 19,
  TABLE_ORDER_COMPLETED: 20,
  TABLE_ORDER_CANCELED: 21,
  TABLE_ORDER_PAYMENT_COMPLETED: 22,

  AWAITING_DELIVERY_RECEIPT: 24,
  DELIVERY_FAILED_NO_CUSTOMER_RESPONSE: 25,
  DELIVERY_ATTEMPTED_ROBOT_ERROR: 26,
  ROBOT_ASSIGNED: 27,
  DELIVERY_FAILED_ROBOT_UNAVAILABLE: 28,
  ROBOT_DROPPING_OFF: 31,
  ORDER_PLACEMENT_ERROR_POS: 29,

  PARTIAL_PICKUP_WAITING: 32,
  PARTIAL_PICKUP_COMPLETED: 33,
  PARTIAL_PICKUP_COMPLETED_AUTO: 34,
} as const

export type OrderStatusCodeValue = (typeof ORDER_STATUS_CODES)[keyof typeof ORDER_STATUS_CODES]

// Create a type-safe mapping of status codes to Korean labels
export const ORDER_STATUS_ENUM: Record<OrderStatusCodeValue, string> = {
  [ORDER_STATUS_CODES.PAYMENT_WAITING]: '결제대기중', // 0
  [ORDER_STATUS_CODES.PAYMENT_COMPLETED]: '결제완료', // 1
  [ORDER_STATUS_CODES.ORDER_ACCEPTED]: '주문접수', // 2

  [ORDER_STATUS_CODES.PICKUP_WAITING]: '픽업대기중', // 3
  [ORDER_STATUS_CODES.PICKUP_COMPLETED]: '픽업완료', // 4
  [ORDER_STATUS_CODES.PICKUP_COMPLETED_AUTO]: '자동픽업완료', // 5

  [ORDER_STATUS_CODES.DELIVERY_REQUESTED]: '배달요청', // 6
  [ORDER_STATUS_CODES.DELIVERY_IN_PROGRESS]: '배달중', // 7
  [ORDER_STATUS_CODES.DELIVERY_COMPLETED]: '배달완료', // 8
  [ORDER_STATUS_CODES.DELIVERY_COMPLETED_AUTO]: '자동배달완료', // 9
  [ORDER_STATUS_CODES.DELIVERY_CANCELED]: '배달취소', // 10

  [ORDER_STATUS_CODES.REFUND_REQUESTED]: '환불요청', // 11
  [ORDER_STATUS_CODES.REFUND_IN_PROGRESS]: '환불처리중', // 12
  [ORDER_STATUS_CODES.REFUND_COMPLETED]: '환불완료', // 13
  [ORDER_STATUS_CODES.REFUND_COMPLETED_AUTO]: '자동환불완료', // 14
  [ORDER_STATUS_CODES.REFUND_FAILED]: '환불실패', // 30

  [ORDER_STATUS_CODES.PAYMENT_INVALID]: '결제검증실패', // 15
  [ORDER_STATUS_CODES.REFUND_IN_PROGRESS_INVALID_PAYMENT]: '환불완료(검증실패)', // 16
  [ORDER_STATUS_CODES.PAYMENT_FAILED]: '결제실패', // 23

  [ORDER_STATUS_CODES.ORDER_ACCEPT_DELAYED]: '주문접수지연', // 17
  [ORDER_STATUS_CODES.PICKUP_RE_REQUESTED]: '픽업재요청', // 18

  [ORDER_STATUS_CODES.TABLE_ORDER_REQUESTED]: '테이블주문접수요청됨', // 19
  [ORDER_STATUS_CODES.TABLE_ORDER_COMPLETED]: '테이블주문접수', // 20
  [ORDER_STATUS_CODES.TABLE_ORDER_CANCELED]: '테이블주문취소', // 21
  [ORDER_STATUS_CODES.TABLE_ORDER_PAYMENT_COMPLETED]: '테이블주문결제완료', // 22

  [ORDER_STATUS_CODES.AWAITING_DELIVERY_RECEIPT]: '수령대기중', // 24
  [ORDER_STATUS_CODES.DELIVERY_FAILED_NO_CUSTOMER_RESPONSE]:
    '배달실패 - 고객응답없음', // 25
  [ORDER_STATUS_CODES.DELIVERY_ATTEMPTED_ROBOT_ERROR]: '배달실패 - 로봇에러', // 26
  [ORDER_STATUS_CODES.ROBOT_ASSIGNED]: '로봇배정성공', // 27
  [ORDER_STATUS_CODES.DELIVERY_FAILED_ROBOT_UNAVAILABLE]:
    '배달실패 - 로봇배정실패', // 28
  [ORDER_STATUS_CODES.ROBOT_DROPPING_OFF]: '로봇하차중', // 31
  [ORDER_STATUS_CODES.ORDER_PLACEMENT_ERROR_POS]: '주문요청실패', // 29

  [ORDER_STATUS_CODES.PARTIAL_PICKUP_WAITING]: '부분픽업대기중', // 32
  [ORDER_STATUS_CODES.PARTIAL_PICKUP_COMPLETED]: '부분픽업완료', // 33
  [ORDER_STATUS_CODES.PARTIAL_PICKUP_COMPLETED_AUTO]: '자동부분픽업완료', // 34
}

interface OrderStatusItem {
  id: OrderStatusCodeValue
  value: string
  name: string
}

// 주문 처리 후 상태들만 포함 (결제 완료 이후의 픽업, 배달, 환불 관련 상태)
// 초기 상태(PAYMENT_WAITING, PAYMENT_COMPLETED, ORDER_ACCEPTED 등)는 제외
export const ORDER_STATUS: OrderStatusItem[] = [
  ORDER_STATUS_CODES.PARTIAL_PICKUP_WAITING,
  ORDER_STATUS_CODES.PICKUP_RE_REQUESTED,
  ORDER_STATUS_CODES.PICKUP_COMPLETED,
  ORDER_STATUS_CODES.PARTIAL_PICKUP_COMPLETED,
  ORDER_STATUS_CODES.PICKUP_COMPLETED_AUTO,
  ORDER_STATUS_CODES.PARTIAL_PICKUP_COMPLETED_AUTO,
  ORDER_STATUS_CODES.DELIVERY_REQUESTED,
  ORDER_STATUS_CODES.ROBOT_ASSIGNED,
  ORDER_STATUS_CODES.DELIVERY_IN_PROGRESS,
  ORDER_STATUS_CODES.AWAITING_DELIVERY_RECEIPT,
  ORDER_STATUS_CODES.ROBOT_DROPPING_OFF,
  ORDER_STATUS_CODES.DELIVERY_COMPLETED,
  ORDER_STATUS_CODES.DELIVERY_COMPLETED_AUTO,
  ORDER_STATUS_CODES.DELIVERY_FAILED_NO_CUSTOMER_RESPONSE,
  ORDER_STATUS_CODES.DELIVERY_ATTEMPTED_ROBOT_ERROR,
  ORDER_STATUS_CODES.DELIVERY_FAILED_ROBOT_UNAVAILABLE,
  ORDER_STATUS_CODES.DELIVERY_CANCELED,
  ORDER_STATUS_CODES.TABLE_ORDER_REQUESTED,
  ORDER_STATUS_CODES.TABLE_ORDER_COMPLETED,
  ORDER_STATUS_CODES.TABLE_ORDER_PAYMENT_COMPLETED,
  ORDER_STATUS_CODES.TABLE_ORDER_CANCELED,
  ORDER_STATUS_CODES.REFUND_REQUESTED,
  ORDER_STATUS_CODES.REFUND_IN_PROGRESS,
  ORDER_STATUS_CODES.REFUND_IN_PROGRESS_INVALID_PAYMENT,
  ORDER_STATUS_CODES.REFUND_COMPLETED,
  ORDER_STATUS_CODES.REFUND_COMPLETED_AUTO,
  ORDER_STATUS_CODES.REFUND_FAILED,
  ORDER_STATUS_CODES.PAYMENT_INVALID,
  ORDER_STATUS_CODES.PAYMENT_FAILED,
].map(status => ({
  id: status,
  value: status.toString(),
  name: ORDER_STATUS_ENUM[status],
}))

// Define status color mapping with CSS custom properties
// Based on Notion database status color definitions
const STATUS_COLORS = {
  WAITING: '#FF8A01',   // 시작 전 - 주황색
  IN_PROGRESS: '#3AA639', // 올바르게 진행 - 초록색
  COMPLETED: '#0085E5', // 완료 - 파란색
  FAILED: '#E3211E',    // 오류 - 빨간색
  REFUNDED: '#8F8F8F',  // 환불 - 회색
  NONE: 'transparent',  // 미표시
} as const

type StatusColorValue = (typeof STATUS_COLORS)[keyof typeof STATUS_COLORS]

// Orange #FF8A01 - 시작 전 상태
const WAITING_STATUS: readonly OrderStatusCodeValue[] = [
  ORDER_STATUS_CODES.PAYMENT_COMPLETED,
  ORDER_STATUS_CODES.ORDER_ACCEPT_DELAYED,
  ORDER_STATUS_CODES.REFUND_IN_PROGRESS_INVALID_PAYMENT,
  ORDER_STATUS_CODES.TABLE_ORDER_REQUESTED,
]

// Green #3AA639 - 진행 중 상태
const IN_PROGRESS_STATUS: readonly OrderStatusCodeValue[] = [
  ORDER_STATUS_CODES.ORDER_ACCEPTED,
  ORDER_STATUS_CODES.PICKUP_WAITING,
  ORDER_STATUS_CODES.PARTIAL_PICKUP_WAITING,
  ORDER_STATUS_CODES.PICKUP_RE_REQUESTED,
  ORDER_STATUS_CODES.PARTIAL_PICKUP_COMPLETED,
  ORDER_STATUS_CODES.PARTIAL_PICKUP_COMPLETED_AUTO,
  ORDER_STATUS_CODES.DELIVERY_REQUESTED,
  ORDER_STATUS_CODES.DELIVERY_IN_PROGRESS,
  ORDER_STATUS_CODES.DELIVERY_CANCELED,
  ORDER_STATUS_CODES.REFUND_REQUESTED,
  ORDER_STATUS_CODES.REFUND_IN_PROGRESS,
  ORDER_STATUS_CODES.AWAITING_DELIVERY_RECEIPT,
  ORDER_STATUS_CODES.ROBOT_ASSIGNED,
  ORDER_STATUS_CODES.ROBOT_DROPPING_OFF,
  ORDER_STATUS_CODES.TABLE_ORDER_COMPLETED,
]

// Blue #0085E5 - 완료 상태
const COMPLETED_STATUS: readonly OrderStatusCodeValue[] = [
  ORDER_STATUS_CODES.PICKUP_COMPLETED,
  ORDER_STATUS_CODES.PICKUP_COMPLETED_AUTO,
  ORDER_STATUS_CODES.DELIVERY_COMPLETED,
  ORDER_STATUS_CODES.DELIVERY_COMPLETED_AUTO,
  ORDER_STATUS_CODES.TABLE_ORDER_CANCELED,
]

// Red #E3211E - 실패/오류 상태
const FAILED_STATUS: readonly OrderStatusCodeValue[] = [
  ORDER_STATUS_CODES.DELIVERY_FAILED_NO_CUSTOMER_RESPONSE,
  ORDER_STATUS_CODES.ORDER_PLACEMENT_ERROR_POS,
  ORDER_STATUS_CODES.REFUND_FAILED,
  ORDER_STATUS_CODES.DELIVERY_ATTEMPTED_ROBOT_ERROR,
  ORDER_STATUS_CODES.DELIVERY_FAILED_ROBOT_UNAVAILABLE,
  ORDER_STATUS_CODES.PAYMENT_INVALID,
  ORDER_STATUS_CODES.PAYMENT_FAILED,
]

// Grey #8F8F8F - 환불 완료 상태
const REFUNDED_STATUS: readonly OrderStatusCodeValue[] = [
  ORDER_STATUS_CODES.REFUND_COMPLETED,
  ORDER_STATUS_CODES.REFUND_COMPLETED_AUTO,
]

// 미표시 - 색상 표시 없음
const NONE_STATUS: readonly OrderStatusCodeValue[] = [
  ORDER_STATUS_CODES.PAYMENT_WAITING,
  ORDER_STATUS_CODES.TABLE_ORDER_PAYMENT_COMPLETED,
]

interface StatusColorMapping {
  statuses: readonly OrderStatusCodeValue[]
  color: StatusColorValue
}

const STATUS_COLOR_MAPPINGS: Record<string, StatusColorMapping> = {
  WAITING: {
    statuses: WAITING_STATUS,
    color: STATUS_COLORS.WAITING,
  },
  IN_PROGRESS: {
    statuses: IN_PROGRESS_STATUS,
    color: STATUS_COLORS.IN_PROGRESS,
  },
  COMPLETED: {
    statuses: COMPLETED_STATUS,
    color: STATUS_COLORS.COMPLETED,
  },
  FAILED: {
    statuses: FAILED_STATUS,
    color: STATUS_COLORS.FAILED,
  },
  REFUNDED: {
    statuses: REFUNDED_STATUS,
    color: STATUS_COLORS.REFUNDED,
  },
  NONE: {
    statuses: NONE_STATUS,
    color: STATUS_COLORS.NONE,
  },
}

export const ORDER_STATUS_COLOR_ENUM: Record<string, StatusColorValue> = Object.entries(
  STATUS_COLOR_MAPPINGS,
).reduce(
  (acc, [_, { statuses, color }]) => ({
    ...acc,
    ...Object.fromEntries(
      statuses.map(status => [ORDER_STATUS_ENUM[status], color]),
    ),
  }),
  {},
)
