/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStatisticsRouteImport } from './routes/_authenticated/statistics'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedMenuManagementRouteImport } from './routes/_authenticated/menu-management'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomerManagementRouteImport } from './routes/_authenticated/customer-management'
import { Route as AuthenticatedBrandManagementRouteImport } from './routes/_authenticated/brand-management'
import { Route as AuthenticatedBenefitManagementRouteImport } from './routes/_authenticated/benefit-management'
import { Route as AuthenticatedDisbursementCustomersIndexRouteImport } from './routes/_authenticated/disbursement-customers/index'
import { Route as AuthenticatedBranchManagementIndexRouteImport } from './routes/_authenticated/branch-management/index'
import { Route as AuthenticatedBranchManagementStoreIdRouteImport } from './routes/_authenticated/branch-management/$storeId'
import { Route as AuthenticatedDisbursementCustomersMenuTypeSetIdRouteImport } from './routes/_authenticated/disbursement-customers/$menuType.$setId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStatisticsRoute = AuthenticatedStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/statistics.lazy').then((d) => d.Route),
)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/orders.lazy').then((d) => d.Route),
)
const AuthenticatedMenuManagementRoute =
  AuthenticatedMenuManagementRouteImport.update({
    id: '/menu-management',
    path: '/menu-management',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/menu-management.lazy').then((d) => d.Route),
  )
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/dashboard.lazy').then((d) => d.Route),
)
const AuthenticatedCustomerManagementRoute =
  AuthenticatedCustomerManagementRouteImport.update({
    id: '/customer-management',
    path: '/customer-management',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/customer-management.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedBrandManagementRoute =
  AuthenticatedBrandManagementRouteImport.update({
    id: '/brand-management',
    path: '/brand-management',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/brand-management.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedBenefitManagementRoute =
  AuthenticatedBenefitManagementRouteImport.update({
    id: '/benefit-management',
    path: '/benefit-management',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/benefit-management.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedDisbursementCustomersIndexRoute =
  AuthenticatedDisbursementCustomersIndexRouteImport.update({
    id: '/disbursement-customers/',
    path: '/disbursement-customers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/disbursement-customers/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedBranchManagementIndexRoute =
  AuthenticatedBranchManagementIndexRouteImport.update({
    id: '/branch-management/',
    path: '/branch-management/',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/branch-management/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedBranchManagementStoreIdRoute =
  AuthenticatedBranchManagementStoreIdRouteImport.update({
    id: '/branch-management/$storeId',
    path: '/branch-management/$storeId',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/branch-management/$storeId.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedDisbursementCustomersMenuTypeSetIdRoute =
  AuthenticatedDisbursementCustomersMenuTypeSetIdRouteImport.update({
    id: '/disbursement-customers/$menuType/$setId',
    path: '/disbursement-customers/$menuType/$setId',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/disbursement-customers/$menuType.$setId.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/benefit-management': typeof AuthenticatedBenefitManagementRoute
  '/brand-management': typeof AuthenticatedBrandManagementRoute
  '/customer-management': typeof AuthenticatedCustomerManagementRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/menu-management': typeof AuthenticatedMenuManagementRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/statistics': typeof AuthenticatedStatisticsRoute
  '/branch-management/$storeId': typeof AuthenticatedBranchManagementStoreIdRoute
  '/branch-management/': typeof AuthenticatedBranchManagementIndexRoute
  '/disbursement-customers/': typeof AuthenticatedDisbursementCustomersIndexRoute
  '/disbursement-customers/$menuType/$setId': typeof AuthenticatedDisbursementCustomersMenuTypeSetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/benefit-management': typeof AuthenticatedBenefitManagementRoute
  '/brand-management': typeof AuthenticatedBrandManagementRoute
  '/customer-management': typeof AuthenticatedCustomerManagementRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/menu-management': typeof AuthenticatedMenuManagementRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/statistics': typeof AuthenticatedStatisticsRoute
  '/branch-management/$storeId': typeof AuthenticatedBranchManagementStoreIdRoute
  '/branch-management': typeof AuthenticatedBranchManagementIndexRoute
  '/disbursement-customers': typeof AuthenticatedDisbursementCustomersIndexRoute
  '/disbursement-customers/$menuType/$setId': typeof AuthenticatedDisbursementCustomersMenuTypeSetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/benefit-management': typeof AuthenticatedBenefitManagementRoute
  '/_authenticated/brand-management': typeof AuthenticatedBrandManagementRoute
  '/_authenticated/customer-management': typeof AuthenticatedCustomerManagementRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/menu-management': typeof AuthenticatedMenuManagementRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/statistics': typeof AuthenticatedStatisticsRoute
  '/_authenticated/branch-management/$storeId': typeof AuthenticatedBranchManagementStoreIdRoute
  '/_authenticated/branch-management/': typeof AuthenticatedBranchManagementIndexRoute
  '/_authenticated/disbursement-customers/': typeof AuthenticatedDisbursementCustomersIndexRoute
  '/_authenticated/disbursement-customers/$menuType/$setId': typeof AuthenticatedDisbursementCustomersMenuTypeSetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/benefit-management'
    | '/brand-management'
    | '/customer-management'
    | '/dashboard'
    | '/menu-management'
    | '/orders'
    | '/statistics'
    | '/branch-management/$storeId'
    | '/branch-management/'
    | '/disbursement-customers/'
    | '/disbursement-customers/$menuType/$setId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/benefit-management'
    | '/brand-management'
    | '/customer-management'
    | '/dashboard'
    | '/menu-management'
    | '/orders'
    | '/statistics'
    | '/branch-management/$storeId'
    | '/branch-management'
    | '/disbursement-customers'
    | '/disbursement-customers/$menuType/$setId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/benefit-management'
    | '/_authenticated/brand-management'
    | '/_authenticated/customer-management'
    | '/_authenticated/dashboard'
    | '/_authenticated/menu-management'
    | '/_authenticated/orders'
    | '/_authenticated/statistics'
    | '/_authenticated/branch-management/$storeId'
    | '/_authenticated/branch-management/'
    | '/_authenticated/disbursement-customers/'
    | '/_authenticated/disbursement-customers/$menuType/$setId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/statistics': {
      id: '/_authenticated/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof AuthenticatedStatisticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/menu-management': {
      id: '/_authenticated/menu-management'
      path: '/menu-management'
      fullPath: '/menu-management'
      preLoaderRoute: typeof AuthenticatedMenuManagementRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customer-management': {
      id: '/_authenticated/customer-management'
      path: '/customer-management'
      fullPath: '/customer-management'
      preLoaderRoute: typeof AuthenticatedCustomerManagementRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/brand-management': {
      id: '/_authenticated/brand-management'
      path: '/brand-management'
      fullPath: '/brand-management'
      preLoaderRoute: typeof AuthenticatedBrandManagementRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/benefit-management': {
      id: '/_authenticated/benefit-management'
      path: '/benefit-management'
      fullPath: '/benefit-management'
      preLoaderRoute: typeof AuthenticatedBenefitManagementRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/disbursement-customers/': {
      id: '/_authenticated/disbursement-customers/'
      path: '/disbursement-customers'
      fullPath: '/disbursement-customers/'
      preLoaderRoute: typeof AuthenticatedDisbursementCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/branch-management/': {
      id: '/_authenticated/branch-management/'
      path: '/branch-management'
      fullPath: '/branch-management/'
      preLoaderRoute: typeof AuthenticatedBranchManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/branch-management/$storeId': {
      id: '/_authenticated/branch-management/$storeId'
      path: '/branch-management/$storeId'
      fullPath: '/branch-management/$storeId'
      preLoaderRoute: typeof AuthenticatedBranchManagementStoreIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/disbursement-customers/$menuType/$setId': {
      id: '/_authenticated/disbursement-customers/$menuType/$setId'
      path: '/disbursement-customers/$menuType/$setId'
      fullPath: '/disbursement-customers/$menuType/$setId'
      preLoaderRoute: typeof AuthenticatedDisbursementCustomersMenuTypeSetIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBenefitManagementRoute: typeof AuthenticatedBenefitManagementRoute
  AuthenticatedBrandManagementRoute: typeof AuthenticatedBrandManagementRoute
  AuthenticatedCustomerManagementRoute: typeof AuthenticatedCustomerManagementRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMenuManagementRoute: typeof AuthenticatedMenuManagementRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedStatisticsRoute: typeof AuthenticatedStatisticsRoute
  AuthenticatedBranchManagementStoreIdRoute: typeof AuthenticatedBranchManagementStoreIdRoute
  AuthenticatedBranchManagementIndexRoute: typeof AuthenticatedBranchManagementIndexRoute
  AuthenticatedDisbursementCustomersIndexRoute: typeof AuthenticatedDisbursementCustomersIndexRoute
  AuthenticatedDisbursementCustomersMenuTypeSetIdRoute: typeof AuthenticatedDisbursementCustomersMenuTypeSetIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBenefitManagementRoute: AuthenticatedBenefitManagementRoute,
  AuthenticatedBrandManagementRoute: AuthenticatedBrandManagementRoute,
  AuthenticatedCustomerManagementRoute: AuthenticatedCustomerManagementRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMenuManagementRoute: AuthenticatedMenuManagementRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedStatisticsRoute: AuthenticatedStatisticsRoute,
  AuthenticatedBranchManagementStoreIdRoute:
    AuthenticatedBranchManagementStoreIdRoute,
  AuthenticatedBranchManagementIndexRoute:
    AuthenticatedBranchManagementIndexRoute,
  AuthenticatedDisbursementCustomersIndexRoute:
    AuthenticatedDisbursementCustomersIndexRoute,
  AuthenticatedDisbursementCustomersMenuTypeSetIdRoute:
    AuthenticatedDisbursementCustomersMenuTypeSetIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
